package com.bw.movie.greendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.movie.greendao.HotFilmDaoBean;
import com.bw.movie.greendao.RelaeseFilmDaoBean;
import com.bw.movie.greendao.ScreenFilmDaoBean;

import com.bw.movie.greendao.greendao.HotFilmDaoBeanDao;
import com.bw.movie.greendao.greendao.RelaeseFilmDaoBeanDao;
import com.bw.movie.greendao.greendao.ScreenFilmDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotFilmDaoBeanDaoConfig;
    private final DaoConfig relaeseFilmDaoBeanDaoConfig;
    private final DaoConfig screenFilmDaoBeanDaoConfig;

    private final HotFilmDaoBeanDao hotFilmDaoBeanDao;
    private final RelaeseFilmDaoBeanDao relaeseFilmDaoBeanDao;
    private final ScreenFilmDaoBeanDao screenFilmDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotFilmDaoBeanDaoConfig = daoConfigMap.get(HotFilmDaoBeanDao.class).clone();
        hotFilmDaoBeanDaoConfig.initIdentityScope(type);

        relaeseFilmDaoBeanDaoConfig = daoConfigMap.get(RelaeseFilmDaoBeanDao.class).clone();
        relaeseFilmDaoBeanDaoConfig.initIdentityScope(type);

        screenFilmDaoBeanDaoConfig = daoConfigMap.get(ScreenFilmDaoBeanDao.class).clone();
        screenFilmDaoBeanDaoConfig.initIdentityScope(type);

        hotFilmDaoBeanDao = new HotFilmDaoBeanDao(hotFilmDaoBeanDaoConfig, this);
        relaeseFilmDaoBeanDao = new RelaeseFilmDaoBeanDao(relaeseFilmDaoBeanDaoConfig, this);
        screenFilmDaoBeanDao = new ScreenFilmDaoBeanDao(screenFilmDaoBeanDaoConfig, this);

        registerDao(HotFilmDaoBean.class, hotFilmDaoBeanDao);
        registerDao(RelaeseFilmDaoBean.class, relaeseFilmDaoBeanDao);
        registerDao(ScreenFilmDaoBean.class, screenFilmDaoBeanDao);
    }
    
    public void clear() {
        hotFilmDaoBeanDaoConfig.clearIdentityScope();
        relaeseFilmDaoBeanDaoConfig.clearIdentityScope();
        screenFilmDaoBeanDaoConfig.clearIdentityScope();
    }

    public HotFilmDaoBeanDao getHotFilmDaoBeanDao() {
        return hotFilmDaoBeanDao;
    }

    public RelaeseFilmDaoBeanDao getRelaeseFilmDaoBeanDao() {
        return relaeseFilmDaoBeanDao;
    }

    public ScreenFilmDaoBeanDao getScreenFilmDaoBeanDao() {
        return screenFilmDaoBeanDao;
    }

}
