package com.bw.movie.greendao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bw.movie.greendao.RelaeseFilmDaoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RELAESE_FILM_DAO_BEAN".
*/
public class RelaeseFilmDaoBeanDao extends AbstractDao<RelaeseFilmDaoBean, Integer> {

    public static final String TABLENAME = "RELAESE_FILM_DAO_BEAN";

    /**
     * Properties of entity RelaeseFilmDaoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FollowMovie = new Property(0, String.class, "followMovie", false, "FOLLOW_MOVIE");
        public final static Property Id = new Property(1, int.class, "id", true, "ID");
        public final static Property ImageUrl = new Property(2, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Rank = new Property(4, int.class, "rank", false, "RANK");
        public final static Property Summary = new Property(5, String.class, "summary", false, "SUMMARY");
        public final static Property ReleaseTimeShow = new Property(6, String.class, "releaseTimeShow", false, "RELEASE_TIME_SHOW");
    }


    public RelaeseFilmDaoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RelaeseFilmDaoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RELAESE_FILM_DAO_BEAN\" (" + //
                "\"FOLLOW_MOVIE\" TEXT," + // 0: followMovie
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 1: id
                "\"IMAGE_URL\" TEXT," + // 2: imageUrl
                "\"NAME\" TEXT," + // 3: name
                "\"RANK\" INTEGER NOT NULL ," + // 4: rank
                "\"SUMMARY\" TEXT," + // 5: summary
                "\"RELEASE_TIME_SHOW\" TEXT);"); // 6: releaseTimeShow
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RELAESE_FILM_DAO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RelaeseFilmDaoBean entity) {
        stmt.clearBindings();
 
        String followMovie = entity.getFollowMovie();
        if (followMovie != null) {
            stmt.bindString(1, followMovie);
        }
        stmt.bindLong(2, entity.getId());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(3, imageUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getRank());
 
        String summary = entity.getSummary();
        if (summary != null) {
            stmt.bindString(6, summary);
        }
 
        String releaseTimeShow = entity.getReleaseTimeShow();
        if (releaseTimeShow != null) {
            stmt.bindString(7, releaseTimeShow);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RelaeseFilmDaoBean entity) {
        stmt.clearBindings();
 
        String followMovie = entity.getFollowMovie();
        if (followMovie != null) {
            stmt.bindString(1, followMovie);
        }
        stmt.bindLong(2, entity.getId());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(3, imageUrl);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getRank());
 
        String summary = entity.getSummary();
        if (summary != null) {
            stmt.bindString(6, summary);
        }
 
        String releaseTimeShow = entity.getReleaseTimeShow();
        if (releaseTimeShow != null) {
            stmt.bindString(7, releaseTimeShow);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 1);
    }    

    @Override
    public RelaeseFilmDaoBean readEntity(Cursor cursor, int offset) {
        RelaeseFilmDaoBean entity = new RelaeseFilmDaoBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // followMovie
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imageUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getInt(offset + 4), // rank
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // summary
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // releaseTimeShow
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RelaeseFilmDaoBean entity, int offset) {
        entity.setFollowMovie(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setImageUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRank(cursor.getInt(offset + 4));
        entity.setSummary(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setReleaseTimeShow(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(RelaeseFilmDaoBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public Integer getKey(RelaeseFilmDaoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RelaeseFilmDaoBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
